// connectors.bal

public final Connector[] & readonly ALL_CONNECTORS = [
    {name: "HubSpot CRM Commerce Orders",                 docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot CRM Commerce Quotes",                 docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot CRM Commerce Taxes",                  docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot CRM Engagement Meeting",              docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot CRM Engagement Notes",                docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot CRM Engagements Calls",               docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot CRM Engagements Communications",      docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot CRM Engagements Email",               docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot CRM Engagements Tasks",               docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot CRM Extensions Timelines",            docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot CRM Extensions Video Conferencing",   docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot CRM Import",                          docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot CRM Lists",                           docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot CRM Object Companies",                docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot CRM Object Contacts",                 docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot CRM Object Deals",                    docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot CRM Object Feedback",                 docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot CRM Object Leads",                    docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot CRM Object Line Items",               docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot CRM Object Products",                 docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot CRM Object Schemas",                  docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot CRM Object Tickets",                  docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot CRM Owners",                          docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot CRM Pipelines",                       docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot CRM Properties",                      docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot Marketing Campaigns",                 docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot Marketing Emails",                    docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot Marketing Events",                    docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot Marketing Forms",                     docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot Marketing Subscriptions",             docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()},
    {name: "HubSpot Marketing Transactional",             docsUrl: "https://github.com/HubSpot/HubSpot-public-api-spec-collection", targetTitle: ()}
];
